CREATE TABLE `blogPosts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`title` varchar(500) NOT NULL,
	`slug` varchar(500) NOT NULL,
	`excerpt` text,
	`content` text NOT NULL,
	`contentType` enum('original','curated','commentary') NOT NULL DEFAULT 'original',
	`sourceUrl` varchar(1024),
	`sourceAuthor` varchar(255),
	`sourcePublication` varchar(255),
	`category` varchar(128),
	`tags` text,
	`coverImage` varchar(512),
	`authorId` int,
	`authorName` varchar(255),
	`status` enum('draft','published') NOT NULL DEFAULT 'draft',
	`publishedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blogPosts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blogPosts_slug_unique` UNIQUE(`slug`)
);
